# Generated by Django 6.1 on 2026-08-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='books.book')),
            ],
        ),
    ]
